USE [master]
GO

/****** Object:  Database [test3]    Script Date: 20-Apr-23 03:59:31 PM ******/
CREATE DATABASE [test3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'test3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CHITAITRUONG01\MSSQL\DATA\test3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'test3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CHITAITRUONG01\MSSQL\DATA\test3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [test3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [test3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [test3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [test3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [test3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [test3] SET ARITHABORT OFF 
GO

ALTER DATABASE [test3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [test3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [test3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [test3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [test3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [test3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [test3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [test3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [test3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [test3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [test3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [test3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [test3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [test3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [test3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [test3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [test3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [test3] SET RECOVERY FULL 
GO

ALTER DATABASE [test3] SET  MULTI_USER 
GO

ALTER DATABASE [test3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [test3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [test3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [test3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [test3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [test3] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [test3] SET QUERY_STORE = OFF
GO

ALTER DATABASE [test3] SET  READ_WRITE 
GO

